### PR TITLE
42-coreos.preset: Enable crio by default

### PR DESCRIPTION
**Pull request by ashcrow**
Replaces https://github.com/openshift/os/pull/169

See https://github.com/coreos/mantle/pull/885#issuecomment-404637101

### CODE REVIEW

**Comment by cgwalters** [comment]
So I have to admit I had not actually played with `cri-o` really before.   I have some questions...


Out of curiosity is there a reason it's not socket activated?

Why does the cli we ship emit a deprecation warning in the default config?

```
# crictl  images
W0712 21:42:58.686957    2041 util_unix.go:75] Using "/var/run/crio/crio.sock" as endpoint is deprecated, please consider using full url format "unix:///var/run/crio/crio.sock".
IMAGE               TAG                 IMAGE ID            SIZE
```

Third: I'd been hoping to not enable `docker.service` by default actually.  Having the service started by default means that if you *do* want to configure it post-startup you need to turn it off.  Of course Ignition fixes this problem, but OTOH we're not today using Ignition for Vagrant.

**Comment by ashcrow** [comment]
> Out of curiosity is there a reason it's not socket activated?
> Why does the cli we ship emit a deprecation warning in the default config?

I'm not sure why, but @mrunalp may be able to answer those questions.

> Third: I'd been hoping to not enable docker.service by default actually.

I'm with you on that. In fact I'm hoping we can drop the package in the compose soon.

> Having the service started by default means that if you do want to configure it post-startup you need to turn it off. Of course Ignition fixes this problem, but OTOH we're not today using Ignition for Vagrant.

That's fair. A different way we could do this is have `kola` testing on `crio` start it up before running tests. But that feels a bit off to me as well.

Thoughts?

**Comment by miabbott** [comment]
> That's fair. A different way we could do this is have kola testing on crio start it up before running tests. But that feels a bit off to me as well.

I did that when testing your PR...it's a one-line change that would allow us to get some basic coverage on `crio`.  I don't think it would be terrible in the short term to get some early coverage.

**Comment by miabbott** [comment]
I think we can enable `crio` by default via these changes, get the answers for @cgwalters questions, and adjust in the future.

Soooo, LGTM

**Pull request merged**
