### PR TITLE
Split off ootpa fork (DO NOT MERGE)

### PR DESCRIPTION
**Pull request by cgwalters**
We really want separate release packages for our separate
streams to help distinguish them; there's a pretty huge difference
at the OS level.

Note that this also fixes a rather large bug in that we were missing
the `99-default-disable.preset`.  I'll do another PR to add that
to the maipo `master` too.

### CODE REVIEW

**Comment by cgwalters** [comment]
I propose we create git branches - take this PR as `ootpa`, and make the existing one `maipo`, then delete the `master` branch.

**Comment by cgwalters** [comment]
I tested this locally using the new coreos-assembler `overrides/rpm` bits btw.

**Comment by jlebon** [comment]
Separate branches seems cleaner to me too and emulates e.g. dist-git workflows as well.

**Comment by cgwalters** [comment]
OK, new `ootpa` branch created.

**Pull request closed without merging**
