### PR TITLE
systemd presets: disable unnecessary services

### PR DESCRIPTION
**Pull request by yuqi-zhang**
Disable sssd, nis-domainname and rpcbind as they should not be
enabled by default.

### CODE REVIEW

**Comment by yuqi-zhang** [comment]
Notes: `sssd` is enabled due to https://bugzilla.redhat.com/show_bug.cgi?id=1578833 , should we be disabling it? (also should we disable sssd-kcm.socket as well?)

Throwing this up mostly for discussion. cc/ @miabbott

**Comment by cgwalters** [comment]
Hmm but if we go this route it is going to permanently fork us from the base `redhat-release` package.  I'm not entirely opposed to that but it feels cleaner to use a separately named override file.

**Comment by miabbott** [comment]
Based on @cgwalters comment and his changes to the `postprocess` section of the RHCOS compose, I think we can close this without merging.

**Comment by yuqi-zhang** [comment]
Yes, closing

**Pull request closed without merging**
